name: delete-deployments-action
description: Delete the outdated Deployments

inputs:
  batch-deletion-rate-limit:
    description: If set, perform the batch deletion while the rate limit is remaining
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
