name: delete-deployments-action
description: Delete the outdated Deployments

inputs:
  batch-deletion-rate-limit:
    description: Stop the batch deletion when the rate limit remaining is less than this value
    required: true
    default: 1000
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js'
